Feature/sc 27301/UI e2e testing
InfuseAI/piperider pull request #265
Opened 2022-07-11 01:14 UTC by jonycfu

** PR checklist **

- [ X] Ensure you have added or ran the appropriate tests for your PR.
- [ X] DCO signed

**What type of PR is this?**
Feature
**What this PR does / why we need it**:
E2E UI Testing (smoke-tests : no blank page breakage)
**Which issue(s) this PR fixes**:
SC 27301
**Special notes for your reviewer**:
Local Working (below); WIP testing on PR event on gh-actions
https://www.loom.com/share/7f576a39d2fd45ff91a06929b3ba4811
**Does this PR introduce a user-facing change?**:
No

NONE

2022-07-11 01:47 UTC, jonycfu commented
The large file sizes are due to the fact that we are committing the raw json files. A further improvement will be made to make it more dynamic in the future, reusing cli to generate said `json` in the project

2022-07-11 04:14 UTC, jonycfu commented
After much thought, I will improve this implementation to generate jsons from piperider cli directly. 
Current state will also include jsons into build (not good)

2022-07-11 06:26 UTC, jonycfu commented
> After much thought, I will improve this implementation to generate jsons from piperider cli directly. Current state will also include jsons into build (not good)

Update: found out that this may require `expect` script to handle the inputs to `init` and `compare-reports` commands. 
Not sure how complicated it is to implement or if it's possible. @ctiml is this possible?

As for the "included jsons into the build" mentioned earlier, I can remove them from `public/` instead. So no issues there. 

The main question is whether we want to version control data json files specifically for UI e2e purposes vs. having the actual profiler cli generate the data to consume in the e2e report tests, which make this a full integration test. Either way, there's a tradeoff between mock data maintenance and scope size (pure FE only + more mocks vs. fully integration test + less mocks)

2022-07-12 00:39 UTC, neighborhood999 requested changes

2022-07-12 01:49 UTC, jonycfu commented on static_report/package.json
> +    "serve:single": "PORT=3000 REACT_APP_SINGLE_REPORT=true react-scripts start",
This actually doesn't change. we will still use 
```
    "start:single": "run-s setup serve:single",
    "start:comparison": "run-s setup serve:comparison",
```

2022-07-12 05:31 UTC, jonycfu commented on static_report/package.json
> +    "serve:single": "PORT=3000 REACT_APP_SINGLE_REPORT=true react-scripts start",
![image](https://user-images.githubusercontent.com/11186480/178415722-d43f61da-cb57-4d8f-a251-1b1a54745214.png)

2022-07-14 01:08 UTC, jonycfu commented
@neighborhood999 @ctiml 
I need a final review from you guys. Build now works. 
Have updated readme section documenting the E2E UI process for Cypress. 

Thanks in advance 🙏

2022-07-14 01:27 UTC, neighborhood999 commented on static_report/package.json
> +    "http-server": "^14.1.1",
Move to  `devDependencies`?

2022-07-14 01:27 UTC, neighborhood999 commented on static_report/package.json
> +    "cypress": "^10.3.0",
Same as the above question.

2022-07-14 02:45 UTC, neighborhood999 approved these changes

2022-07-14 02:46 UTC, merged