[Feature] compare with recipes
InfuseAI/piperider pull request #586
Opened 2023-02-06 06:29 UTC by qrtt1

**PR checklist**

- [ ] Ensure you have added or ran the appropriate tests for your PR.
- [x] DCO signed

**What type of PR is this?**

feature added

**What this PR does / why we need it**:

New comparison strategy with the recipe configuration

**Which issue(s) this PR fixes**:

sc-30452

**Special notes for your reviewer**:

TBD

**Does this PR introduce a user-facing change?**:

2023-02-10 11:07 UTC, popcornylu commented
For branch switching logic, can we use merge-base, rather than branch latest commit?
```
COMMIT=$(git merge-base $(git rev-parse HEAD) main)     
```

github pull request use the three dot version diff. see [github compare branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests#three-dot-and-two-dot-git-diff-comparisons)

2023-02-13 08:29 UTC, popcornylu requested changes
1. If the git working directory is dirty, don't print the trackback
2. If there is no `command` or `commands` in piperider settings, the command shoud fail.
3. Remove the `--dbt-state target/` from the generated default recipe
4. `piperider compare --recipe xyz` should not show the dbt project select (if there are multiple dbt project)    i use ` git clone git@github.com:dbt-labs/dbt-core.git git_repo   ` in the git-repo-analytics repo

2023-02-14 06:24 UTC, kentwelcome commented on piperider_cli/configuration.py
> +            'target': target_name,
fixed

2023-02-14 06:41 UTC, kentwelcome commented
All the code review issues are fixed!

2023-02-14 16:38 UTC, merged